global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'orchestrator'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['orchestrator:5000']
    scrape_interval: 5s
    scrape_timeout: 4s

  - job_name: 'node-exporter'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s
    scrape_timeout: 4s

  - job_name: 'prometheus'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    scrape_timeout: 4s